### ISSUE TITLE
받침 추가 필요

### ISSUE THREAD

**Issue by ywan311** [ywan311/translate#1]
- [x] ㄱ
- [x] ㄲ
- [x] ㄴ
- [x] ㄷ
- [x] ㄸ
- [x] ㄹ
- [x] ㅁ
- [x] ㅂ
- [x] ㅃ
- [x] ㅅ
- [x] ㅆ
- [x] ㅇ
- [x] ㅈ
- [x] ㅉ
- [x] ㅊ
- [x] ㅋ
- [x] ㅌ
- [x] ㅍ
- [x] ㅎ

**Comment by IMYMEMINEU** [comment]
1킁 1킁(+1일 1킁)
